// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.7
// source: google/cloud/dialogflow/v2beta1/conversational_training_team.proto

package dialogflowpb

import (
	iampb "cloud.google.com/go/iam/apiv1/iampb"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConversationalTrainingTeams_CreateConversationalTrainingTeam_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/CreateConversationalTrainingTeam"
	ConversationalTrainingTeams_GetConversationalTrainingTeam_FullMethodName    = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/GetConversationalTrainingTeam"
	ConversationalTrainingTeams_ListConversationalTrainingTeams_FullMethodName  = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/ListConversationalTrainingTeams"
	ConversationalTrainingTeams_DeleteConversationalTrainingTeam_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/DeleteConversationalTrainingTeam"
	ConversationalTrainingTeams_UpdateConversationalTrainingTeam_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/UpdateConversationalTrainingTeam"
	ConversationalTrainingTeams_SetIamPolicy_FullMethodName                     = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/SetIamPolicy"
	ConversationalTrainingTeams_GetIamPolicy_FullMethodName                     = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/GetIamPolicy"
	ConversationalTrainingTeams_TestIamPermissions_FullMethodName               = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams/TestIamPermissions"
)

// ConversationalTrainingTeamsClient is the client API for ConversationalTrainingTeams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationalTrainingTeamsClient interface {
	// Creates a conversational training team.
	CreateConversationalTrainingTeam(ctx context.Context, in *CreateConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error)
	// Retrieves a conversational training team.
	GetConversationalTrainingTeam(ctx context.Context, in *GetConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error)
	// Lists conversational training teams.
	ListConversationalTrainingTeams(ctx context.Context, in *ListConversationalTrainingTeamsRequest, opts ...grpc.CallOption) (*ListConversationalTrainingTeamsResponse, error)
	// Deletes a conversational training team.
	DeleteConversationalTrainingTeam(ctx context.Context, in *DeleteConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Updates a conversational training team.
	UpdateConversationalTrainingTeam(ctx context.Context, in *UpdateConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error)
	// Sets Iam Policy for given conversationalTrainingTeam.
	SetIamPolicy(ctx context.Context, in *iampb.SetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error)
	// Gets Iam Policy for given conversationalTrainingTeam.
	GetIamPolicy(ctx context.Context, in *iampb.GetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error)
	// Test permissions for given conversationalTrainingTeam.
	TestIamPermissions(ctx context.Context, in *iampb.TestIamPermissionsRequest, opts ...grpc.CallOption) (*iampb.TestIamPermissionsResponse, error)
}

type conversationalTrainingTeamsClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationalTrainingTeamsClient(cc grpc.ClientConnInterface) ConversationalTrainingTeamsClient {
	return &conversationalTrainingTeamsClient{cc}
}

func (c *conversationalTrainingTeamsClient) CreateConversationalTrainingTeam(ctx context.Context, in *CreateConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error) {
	out := new(ConversationalTrainingTeam)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_CreateConversationalTrainingTeam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) GetConversationalTrainingTeam(ctx context.Context, in *GetConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error) {
	out := new(ConversationalTrainingTeam)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_GetConversationalTrainingTeam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) ListConversationalTrainingTeams(ctx context.Context, in *ListConversationalTrainingTeamsRequest, opts ...grpc.CallOption) (*ListConversationalTrainingTeamsResponse, error) {
	out := new(ListConversationalTrainingTeamsResponse)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_ListConversationalTrainingTeams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) DeleteConversationalTrainingTeam(ctx context.Context, in *DeleteConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_DeleteConversationalTrainingTeam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) UpdateConversationalTrainingTeam(ctx context.Context, in *UpdateConversationalTrainingTeamRequest, opts ...grpc.CallOption) (*ConversationalTrainingTeam, error) {
	out := new(ConversationalTrainingTeam)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_UpdateConversationalTrainingTeam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) SetIamPolicy(ctx context.Context, in *iampb.SetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error) {
	out := new(iampb.Policy)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_SetIamPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) GetIamPolicy(ctx context.Context, in *iampb.GetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error) {
	out := new(iampb.Policy)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_GetIamPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingTeamsClient) TestIamPermissions(ctx context.Context, in *iampb.TestIamPermissionsRequest, opts ...grpc.CallOption) (*iampb.TestIamPermissionsResponse, error) {
	out := new(iampb.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, ConversationalTrainingTeams_TestIamPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationalTrainingTeamsServer is the server API for ConversationalTrainingTeams service.
// All implementations should embed UnimplementedConversationalTrainingTeamsServer
// for forward compatibility
type ConversationalTrainingTeamsServer interface {
	// Creates a conversational training team.
	CreateConversationalTrainingTeam(context.Context, *CreateConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error)
	// Retrieves a conversational training team.
	GetConversationalTrainingTeam(context.Context, *GetConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error)
	// Lists conversational training teams.
	ListConversationalTrainingTeams(context.Context, *ListConversationalTrainingTeamsRequest) (*ListConversationalTrainingTeamsResponse, error)
	// Deletes a conversational training team.
	DeleteConversationalTrainingTeam(context.Context, *DeleteConversationalTrainingTeamRequest) (*emptypb.Empty, error)
	// Updates a conversational training team.
	UpdateConversationalTrainingTeam(context.Context, *UpdateConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error)
	// Sets Iam Policy for given conversationalTrainingTeam.
	SetIamPolicy(context.Context, *iampb.SetIamPolicyRequest) (*iampb.Policy, error)
	// Gets Iam Policy for given conversationalTrainingTeam.
	GetIamPolicy(context.Context, *iampb.GetIamPolicyRequest) (*iampb.Policy, error)
	// Test permissions for given conversationalTrainingTeam.
	TestIamPermissions(context.Context, *iampb.TestIamPermissionsRequest) (*iampb.TestIamPermissionsResponse, error)
}

// UnimplementedConversationalTrainingTeamsServer should be embedded to have forward compatible implementations.
type UnimplementedConversationalTrainingTeamsServer struct {
}

func (UnimplementedConversationalTrainingTeamsServer) CreateConversationalTrainingTeam(context.Context, *CreateConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversationalTrainingTeam not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) GetConversationalTrainingTeam(context.Context, *GetConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationalTrainingTeam not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) ListConversationalTrainingTeams(context.Context, *ListConversationalTrainingTeamsRequest) (*ListConversationalTrainingTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversationalTrainingTeams not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) DeleteConversationalTrainingTeam(context.Context, *DeleteConversationalTrainingTeamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversationalTrainingTeam not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) UpdateConversationalTrainingTeam(context.Context, *UpdateConversationalTrainingTeamRequest) (*ConversationalTrainingTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationalTrainingTeam not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) SetIamPolicy(context.Context, *iampb.SetIamPolicyRequest) (*iampb.Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) GetIamPolicy(context.Context, *iampb.GetIamPolicyRequest) (*iampb.Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedConversationalTrainingTeamsServer) TestIamPermissions(context.Context, *iampb.TestIamPermissionsRequest) (*iampb.TestIamPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestIamPermissions not implemented")
}

// UnsafeConversationalTrainingTeamsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationalTrainingTeamsServer will
// result in compilation errors.
type UnsafeConversationalTrainingTeamsServer interface {
	mustEmbedUnimplementedConversationalTrainingTeamsServer()
}

func RegisterConversationalTrainingTeamsServer(s grpc.ServiceRegistrar, srv ConversationalTrainingTeamsServer) {
	s.RegisterService(&ConversationalTrainingTeams_ServiceDesc, srv)
}

func _ConversationalTrainingTeams_CreateConversationalTrainingTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationalTrainingTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).CreateConversationalTrainingTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_CreateConversationalTrainingTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).CreateConversationalTrainingTeam(ctx, req.(*CreateConversationalTrainingTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_GetConversationalTrainingTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationalTrainingTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).GetConversationalTrainingTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_GetConversationalTrainingTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).GetConversationalTrainingTeam(ctx, req.(*GetConversationalTrainingTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_ListConversationalTrainingTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationalTrainingTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).ListConversationalTrainingTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_ListConversationalTrainingTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).ListConversationalTrainingTeams(ctx, req.(*ListConversationalTrainingTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_DeleteConversationalTrainingTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationalTrainingTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).DeleteConversationalTrainingTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_DeleteConversationalTrainingTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).DeleteConversationalTrainingTeam(ctx, req.(*DeleteConversationalTrainingTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_UpdateConversationalTrainingTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationalTrainingTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).UpdateConversationalTrainingTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_UpdateConversationalTrainingTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).UpdateConversationalTrainingTeam(ctx, req.(*UpdateConversationalTrainingTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).SetIamPolicy(ctx, req.(*iampb.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).GetIamPolicy(ctx, req.(*iampb.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingTeams_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingTeamsServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingTeams_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingTeamsServer).TestIamPermissions(ctx, req.(*iampb.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationalTrainingTeams_ServiceDesc is the grpc.ServiceDesc for ConversationalTrainingTeams service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationalTrainingTeams_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.ConversationalTrainingTeams",
	HandlerType: (*ConversationalTrainingTeamsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversationalTrainingTeam",
			Handler:    _ConversationalTrainingTeams_CreateConversationalTrainingTeam_Handler,
		},
		{
			MethodName: "GetConversationalTrainingTeam",
			Handler:    _ConversationalTrainingTeams_GetConversationalTrainingTeam_Handler,
		},
		{
			MethodName: "ListConversationalTrainingTeams",
			Handler:    _ConversationalTrainingTeams_ListConversationalTrainingTeams_Handler,
		},
		{
			MethodName: "DeleteConversationalTrainingTeam",
			Handler:    _ConversationalTrainingTeams_DeleteConversationalTrainingTeam_Handler,
		},
		{
			MethodName: "UpdateConversationalTrainingTeam",
			Handler:    _ConversationalTrainingTeams_UpdateConversationalTrainingTeam_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _ConversationalTrainingTeams_SetIamPolicy_Handler,
		},
		{
			MethodName: "GetIamPolicy",
			Handler:    _ConversationalTrainingTeams_GetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _ConversationalTrainingTeams_TestIamPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/dialogflow/v2beta1/conversational_training_team.proto",
}
