// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.7
// source: google/cloud/dialogflow/v2beta1/conversational_training_member.proto

package dialogflowpb

import (
	iampb "cloud.google.com/go/iam/apiv1/iampb"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConversationalTrainingMembers_CreateConversationalTrainingMember_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/CreateConversationalTrainingMember"
	ConversationalTrainingMembers_GetConversationalTrainingMember_FullMethodName    = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/GetConversationalTrainingMember"
	ConversationalTrainingMembers_ListConversationalTrainingMembers_FullMethodName  = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/ListConversationalTrainingMembers"
	ConversationalTrainingMembers_DeleteConversationalTrainingMember_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/DeleteConversationalTrainingMember"
	ConversationalTrainingMembers_UpdateConversationalTrainingMember_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/UpdateConversationalTrainingMember"
	ConversationalTrainingMembers_SetIamPolicy_FullMethodName                       = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/SetIamPolicy"
	ConversationalTrainingMembers_GetIamPolicy_FullMethodName                       = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/GetIamPolicy"
	ConversationalTrainingMembers_TestIamPermissions_FullMethodName                 = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers/TestIamPermissions"
)

// ConversationalTrainingMembersClient is the client API for ConversationalTrainingMembers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationalTrainingMembersClient interface {
	// Creates a conversational training member.
	CreateConversationalTrainingMember(ctx context.Context, in *CreateConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error)
	// Retrieves a conversational training member.
	GetConversationalTrainingMember(ctx context.Context, in *GetConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error)
	// Lists conversational training members. Supports cross collection listing by
	// specifying `-` as the team ID (AIP 159).
	ListConversationalTrainingMembers(ctx context.Context, in *ListConversationalTrainingMembersRequest, opts ...grpc.CallOption) (*ListConversationalTrainingMembersResponse, error)
	// Deletes a conversational training member.
	DeleteConversationalTrainingMember(ctx context.Context, in *DeleteConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Updates a conversational training member.
	UpdateConversationalTrainingMember(ctx context.Context, in *UpdateConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error)
	// Sets Iam Policy for given conversationalTrainingMember.
	SetIamPolicy(ctx context.Context, in *iampb.SetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error)
	// Gets Iam Policy for given conversationalTrainingMember.
	GetIamPolicy(ctx context.Context, in *iampb.GetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error)
	// Test permissions for given conversationalTrainingMember.
	TestIamPermissions(ctx context.Context, in *iampb.TestIamPermissionsRequest, opts ...grpc.CallOption) (*iampb.TestIamPermissionsResponse, error)
}

type conversationalTrainingMembersClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationalTrainingMembersClient(cc grpc.ClientConnInterface) ConversationalTrainingMembersClient {
	return &conversationalTrainingMembersClient{cc}
}

func (c *conversationalTrainingMembersClient) CreateConversationalTrainingMember(ctx context.Context, in *CreateConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error) {
	out := new(ConversationalTrainingMember)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_CreateConversationalTrainingMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) GetConversationalTrainingMember(ctx context.Context, in *GetConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error) {
	out := new(ConversationalTrainingMember)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_GetConversationalTrainingMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) ListConversationalTrainingMembers(ctx context.Context, in *ListConversationalTrainingMembersRequest, opts ...grpc.CallOption) (*ListConversationalTrainingMembersResponse, error) {
	out := new(ListConversationalTrainingMembersResponse)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_ListConversationalTrainingMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) DeleteConversationalTrainingMember(ctx context.Context, in *DeleteConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_DeleteConversationalTrainingMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) UpdateConversationalTrainingMember(ctx context.Context, in *UpdateConversationalTrainingMemberRequest, opts ...grpc.CallOption) (*ConversationalTrainingMember, error) {
	out := new(ConversationalTrainingMember)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_UpdateConversationalTrainingMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) SetIamPolicy(ctx context.Context, in *iampb.SetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error) {
	out := new(iampb.Policy)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_SetIamPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) GetIamPolicy(ctx context.Context, in *iampb.GetIamPolicyRequest, opts ...grpc.CallOption) (*iampb.Policy, error) {
	out := new(iampb.Policy)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_GetIamPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingMembersClient) TestIamPermissions(ctx context.Context, in *iampb.TestIamPermissionsRequest, opts ...grpc.CallOption) (*iampb.TestIamPermissionsResponse, error) {
	out := new(iampb.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, ConversationalTrainingMembers_TestIamPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationalTrainingMembersServer is the server API for ConversationalTrainingMembers service.
// All implementations should embed UnimplementedConversationalTrainingMembersServer
// for forward compatibility
type ConversationalTrainingMembersServer interface {
	// Creates a conversational training member.
	CreateConversationalTrainingMember(context.Context, *CreateConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error)
	// Retrieves a conversational training member.
	GetConversationalTrainingMember(context.Context, *GetConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error)
	// Lists conversational training members. Supports cross collection listing by
	// specifying `-` as the team ID (AIP 159).
	ListConversationalTrainingMembers(context.Context, *ListConversationalTrainingMembersRequest) (*ListConversationalTrainingMembersResponse, error)
	// Deletes a conversational training member.
	DeleteConversationalTrainingMember(context.Context, *DeleteConversationalTrainingMemberRequest) (*emptypb.Empty, error)
	// Updates a conversational training member.
	UpdateConversationalTrainingMember(context.Context, *UpdateConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error)
	// Sets Iam Policy for given conversationalTrainingMember.
	SetIamPolicy(context.Context, *iampb.SetIamPolicyRequest) (*iampb.Policy, error)
	// Gets Iam Policy for given conversationalTrainingMember.
	GetIamPolicy(context.Context, *iampb.GetIamPolicyRequest) (*iampb.Policy, error)
	// Test permissions for given conversationalTrainingMember.
	TestIamPermissions(context.Context, *iampb.TestIamPermissionsRequest) (*iampb.TestIamPermissionsResponse, error)
}

// UnimplementedConversationalTrainingMembersServer should be embedded to have forward compatible implementations.
type UnimplementedConversationalTrainingMembersServer struct {
}

func (UnimplementedConversationalTrainingMembersServer) CreateConversationalTrainingMember(context.Context, *CreateConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversationalTrainingMember not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) GetConversationalTrainingMember(context.Context, *GetConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationalTrainingMember not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) ListConversationalTrainingMembers(context.Context, *ListConversationalTrainingMembersRequest) (*ListConversationalTrainingMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversationalTrainingMembers not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) DeleteConversationalTrainingMember(context.Context, *DeleteConversationalTrainingMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversationalTrainingMember not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) UpdateConversationalTrainingMember(context.Context, *UpdateConversationalTrainingMemberRequest) (*ConversationalTrainingMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationalTrainingMember not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) SetIamPolicy(context.Context, *iampb.SetIamPolicyRequest) (*iampb.Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIamPolicy not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) GetIamPolicy(context.Context, *iampb.GetIamPolicyRequest) (*iampb.Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIamPolicy not implemented")
}
func (UnimplementedConversationalTrainingMembersServer) TestIamPermissions(context.Context, *iampb.TestIamPermissionsRequest) (*iampb.TestIamPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestIamPermissions not implemented")
}

// UnsafeConversationalTrainingMembersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationalTrainingMembersServer will
// result in compilation errors.
type UnsafeConversationalTrainingMembersServer interface {
	mustEmbedUnimplementedConversationalTrainingMembersServer()
}

func RegisterConversationalTrainingMembersServer(s grpc.ServiceRegistrar, srv ConversationalTrainingMembersServer) {
	s.RegisterService(&ConversationalTrainingMembers_ServiceDesc, srv)
}

func _ConversationalTrainingMembers_CreateConversationalTrainingMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationalTrainingMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).CreateConversationalTrainingMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_CreateConversationalTrainingMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).CreateConversationalTrainingMember(ctx, req.(*CreateConversationalTrainingMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_GetConversationalTrainingMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationalTrainingMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).GetConversationalTrainingMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_GetConversationalTrainingMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).GetConversationalTrainingMember(ctx, req.(*GetConversationalTrainingMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_ListConversationalTrainingMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationalTrainingMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).ListConversationalTrainingMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_ListConversationalTrainingMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).ListConversationalTrainingMembers(ctx, req.(*ListConversationalTrainingMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_DeleteConversationalTrainingMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationalTrainingMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).DeleteConversationalTrainingMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_DeleteConversationalTrainingMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).DeleteConversationalTrainingMember(ctx, req.(*DeleteConversationalTrainingMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_UpdateConversationalTrainingMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationalTrainingMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).UpdateConversationalTrainingMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_UpdateConversationalTrainingMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).UpdateConversationalTrainingMember(ctx, req.(*UpdateConversationalTrainingMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_SetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).SetIamPolicy(ctx, req.(*iampb.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_GetIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).GetIamPolicy(ctx, req.(*iampb.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingMembers_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iampb.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingMembersServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingMembers_TestIamPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingMembersServer).TestIamPermissions(ctx, req.(*iampb.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationalTrainingMembers_ServiceDesc is the grpc.ServiceDesc for ConversationalTrainingMembers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationalTrainingMembers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.ConversationalTrainingMembers",
	HandlerType: (*ConversationalTrainingMembersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversationalTrainingMember",
			Handler:    _ConversationalTrainingMembers_CreateConversationalTrainingMember_Handler,
		},
		{
			MethodName: "GetConversationalTrainingMember",
			Handler:    _ConversationalTrainingMembers_GetConversationalTrainingMember_Handler,
		},
		{
			MethodName: "ListConversationalTrainingMembers",
			Handler:    _ConversationalTrainingMembers_ListConversationalTrainingMembers_Handler,
		},
		{
			MethodName: "DeleteConversationalTrainingMember",
			Handler:    _ConversationalTrainingMembers_DeleteConversationalTrainingMember_Handler,
		},
		{
			MethodName: "UpdateConversationalTrainingMember",
			Handler:    _ConversationalTrainingMembers_UpdateConversationalTrainingMember_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _ConversationalTrainingMembers_SetIamPolicy_Handler,
		},
		{
			MethodName: "GetIamPolicy",
			Handler:    _ConversationalTrainingMembers_GetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _ConversationalTrainingMembers_TestIamPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/dialogflow/v2beta1/conversational_training_member.proto",
}
