// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.7
// source: google/cloud/dialogflow/v2beta1/conversational_training_module.proto

package dialogflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConversationalTrainingModules_CreateConversationalTrainingModule_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingModules/CreateConversationalTrainingModule"
	ConversationalTrainingModules_GetConversationalTrainingModule_FullMethodName    = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingModules/GetConversationalTrainingModule"
	ConversationalTrainingModules_ListConversationalTrainingModules_FullMethodName  = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingModules/ListConversationalTrainingModules"
	ConversationalTrainingModules_DeleteConversationalTrainingModule_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingModules/DeleteConversationalTrainingModule"
	ConversationalTrainingModules_UpdateConversationalTrainingModule_FullMethodName = "/google.cloud.dialogflow.v2beta1.ConversationalTrainingModules/UpdateConversationalTrainingModule"
)

// ConversationalTrainingModulesClient is the client API for ConversationalTrainingModules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationalTrainingModulesClient interface {
	// Creates a conversational training module.
	CreateConversationalTrainingModule(ctx context.Context, in *CreateConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error)
	// Retrieves a conversational training module.
	GetConversationalTrainingModule(ctx context.Context, in *GetConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error)
	// Lists conversational training modules.
	ListConversationalTrainingModules(ctx context.Context, in *ListConversationalTrainingModulesRequest, opts ...grpc.CallOption) (*ListConversationalTrainingModulesResponse, error)
	// Deletes a conversational training module.
	DeleteConversationalTrainingModule(ctx context.Context, in *DeleteConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Updates a conversational training module.
	UpdateConversationalTrainingModule(ctx context.Context, in *UpdateConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error)
}

type conversationalTrainingModulesClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationalTrainingModulesClient(cc grpc.ClientConnInterface) ConversationalTrainingModulesClient {
	return &conversationalTrainingModulesClient{cc}
}

func (c *conversationalTrainingModulesClient) CreateConversationalTrainingModule(ctx context.Context, in *CreateConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error) {
	out := new(ConversationalTrainingModule)
	err := c.cc.Invoke(ctx, ConversationalTrainingModules_CreateConversationalTrainingModule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingModulesClient) GetConversationalTrainingModule(ctx context.Context, in *GetConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error) {
	out := new(ConversationalTrainingModule)
	err := c.cc.Invoke(ctx, ConversationalTrainingModules_GetConversationalTrainingModule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingModulesClient) ListConversationalTrainingModules(ctx context.Context, in *ListConversationalTrainingModulesRequest, opts ...grpc.CallOption) (*ListConversationalTrainingModulesResponse, error) {
	out := new(ListConversationalTrainingModulesResponse)
	err := c.cc.Invoke(ctx, ConversationalTrainingModules_ListConversationalTrainingModules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingModulesClient) DeleteConversationalTrainingModule(ctx context.Context, in *DeleteConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConversationalTrainingModules_DeleteConversationalTrainingModule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationalTrainingModulesClient) UpdateConversationalTrainingModule(ctx context.Context, in *UpdateConversationalTrainingModuleRequest, opts ...grpc.CallOption) (*ConversationalTrainingModule, error) {
	out := new(ConversationalTrainingModule)
	err := c.cc.Invoke(ctx, ConversationalTrainingModules_UpdateConversationalTrainingModule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationalTrainingModulesServer is the server API for ConversationalTrainingModules service.
// All implementations should embed UnimplementedConversationalTrainingModulesServer
// for forward compatibility
type ConversationalTrainingModulesServer interface {
	// Creates a conversational training module.
	CreateConversationalTrainingModule(context.Context, *CreateConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error)
	// Retrieves a conversational training module.
	GetConversationalTrainingModule(context.Context, *GetConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error)
	// Lists conversational training modules.
	ListConversationalTrainingModules(context.Context, *ListConversationalTrainingModulesRequest) (*ListConversationalTrainingModulesResponse, error)
	// Deletes a conversational training module.
	DeleteConversationalTrainingModule(context.Context, *DeleteConversationalTrainingModuleRequest) (*emptypb.Empty, error)
	// Updates a conversational training module.
	UpdateConversationalTrainingModule(context.Context, *UpdateConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error)
}

// UnimplementedConversationalTrainingModulesServer should be embedded to have forward compatible implementations.
type UnimplementedConversationalTrainingModulesServer struct {
}

func (UnimplementedConversationalTrainingModulesServer) CreateConversationalTrainingModule(context.Context, *CreateConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversationalTrainingModule not implemented")
}
func (UnimplementedConversationalTrainingModulesServer) GetConversationalTrainingModule(context.Context, *GetConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationalTrainingModule not implemented")
}
func (UnimplementedConversationalTrainingModulesServer) ListConversationalTrainingModules(context.Context, *ListConversationalTrainingModulesRequest) (*ListConversationalTrainingModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversationalTrainingModules not implemented")
}
func (UnimplementedConversationalTrainingModulesServer) DeleteConversationalTrainingModule(context.Context, *DeleteConversationalTrainingModuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversationalTrainingModule not implemented")
}
func (UnimplementedConversationalTrainingModulesServer) UpdateConversationalTrainingModule(context.Context, *UpdateConversationalTrainingModuleRequest) (*ConversationalTrainingModule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationalTrainingModule not implemented")
}

// UnsafeConversationalTrainingModulesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationalTrainingModulesServer will
// result in compilation errors.
type UnsafeConversationalTrainingModulesServer interface {
	mustEmbedUnimplementedConversationalTrainingModulesServer()
}

func RegisterConversationalTrainingModulesServer(s grpc.ServiceRegistrar, srv ConversationalTrainingModulesServer) {
	s.RegisterService(&ConversationalTrainingModules_ServiceDesc, srv)
}

func _ConversationalTrainingModules_CreateConversationalTrainingModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationalTrainingModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingModulesServer).CreateConversationalTrainingModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingModules_CreateConversationalTrainingModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingModulesServer).CreateConversationalTrainingModule(ctx, req.(*CreateConversationalTrainingModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingModules_GetConversationalTrainingModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationalTrainingModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingModulesServer).GetConversationalTrainingModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingModules_GetConversationalTrainingModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingModulesServer).GetConversationalTrainingModule(ctx, req.(*GetConversationalTrainingModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingModules_ListConversationalTrainingModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationalTrainingModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingModulesServer).ListConversationalTrainingModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingModules_ListConversationalTrainingModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingModulesServer).ListConversationalTrainingModules(ctx, req.(*ListConversationalTrainingModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingModules_DeleteConversationalTrainingModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationalTrainingModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingModulesServer).DeleteConversationalTrainingModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingModules_DeleteConversationalTrainingModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingModulesServer).DeleteConversationalTrainingModule(ctx, req.(*DeleteConversationalTrainingModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationalTrainingModules_UpdateConversationalTrainingModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationalTrainingModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationalTrainingModulesServer).UpdateConversationalTrainingModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationalTrainingModules_UpdateConversationalTrainingModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationalTrainingModulesServer).UpdateConversationalTrainingModule(ctx, req.(*UpdateConversationalTrainingModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationalTrainingModules_ServiceDesc is the grpc.ServiceDesc for ConversationalTrainingModules service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationalTrainingModules_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.ConversationalTrainingModules",
	HandlerType: (*ConversationalTrainingModulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversationalTrainingModule",
			Handler:    _ConversationalTrainingModules_CreateConversationalTrainingModule_Handler,
		},
		{
			MethodName: "GetConversationalTrainingModule",
			Handler:    _ConversationalTrainingModules_GetConversationalTrainingModule_Handler,
		},
		{
			MethodName: "ListConversationalTrainingModules",
			Handler:    _ConversationalTrainingModules_ListConversationalTrainingModules_Handler,
		},
		{
			MethodName: "DeleteConversationalTrainingModule",
			Handler:    _ConversationalTrainingModules_DeleteConversationalTrainingModule_Handler,
		},
		{
			MethodName: "UpdateConversationalTrainingModule",
			Handler:    _ConversationalTrainingModules_UpdateConversationalTrainingModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/dialogflow/v2beta1/conversational_training_module.proto",
}
