// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.7
// source: google/cloud/dialogflow/v2beta1/phone_number_order.proto

package dialogflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PhoneNumberOrders_CreatePhoneNumberOrder_FullMethodName = "/google.cloud.dialogflow.v2beta1.PhoneNumberOrders/CreatePhoneNumberOrder"
	PhoneNumberOrders_GetPhoneNumberOrder_FullMethodName    = "/google.cloud.dialogflow.v2beta1.PhoneNumberOrders/GetPhoneNumberOrder"
	PhoneNumberOrders_ListPhoneNumberOrders_FullMethodName  = "/google.cloud.dialogflow.v2beta1.PhoneNumberOrders/ListPhoneNumberOrders"
	PhoneNumberOrders_UpdatePhoneNumberOrder_FullMethodName = "/google.cloud.dialogflow.v2beta1.PhoneNumberOrders/UpdatePhoneNumberOrder"
	PhoneNumberOrders_CancelPhoneNumberOrder_FullMethodName = "/google.cloud.dialogflow.v2beta1.PhoneNumberOrders/CancelPhoneNumberOrder"
)

// PhoneNumberOrdersClient is the client API for PhoneNumberOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneNumberOrdersClient interface {
	// Creates an order to request phone numbers be added to a project.
	// The initial `LifecycleState` of a newly created order is
	// [PENDING][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.PENDING].
	CreatePhoneNumberOrder(ctx context.Context, in *CreatePhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error)
	// Returns a specific `PhoneNumberOrder`.
	GetPhoneNumberOrder(ctx context.Context, in *GetPhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error)
	// Lists of all `PhoneNumberOrder` resources in the specified project.
	ListPhoneNumberOrders(ctx context.Context, in *ListPhoneNumberOrdersRequest, opts ...grpc.CallOption) (*ListPhoneNumberOrdersResponse, error)
	// Updates the specified `PhoneNumberOrder` resource.
	// Returns an error if the order is in state
	// [IN_PROGRESS][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.IN_PROGRESS]
	// or
	// [COMPLETED][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.COMPLETED].
	UpdatePhoneNumberOrder(ctx context.Context, in *UpdatePhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error)
	// Cancels an `PhoneNumberOrder`.
	// Returns an error if the order is in state
	// [IN_PROGRESS][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.IN_PROGRESS]
	// or
	// [COMPLETED][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.COMPLETED].
	CancelPhoneNumberOrder(ctx context.Context, in *CancelPhoneNumberOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type phoneNumberOrdersClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneNumberOrdersClient(cc grpc.ClientConnInterface) PhoneNumberOrdersClient {
	return &phoneNumberOrdersClient{cc}
}

func (c *phoneNumberOrdersClient) CreatePhoneNumberOrder(ctx context.Context, in *CreatePhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error) {
	out := new(PhoneNumberOrder)
	err := c.cc.Invoke(ctx, PhoneNumberOrders_CreatePhoneNumberOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneNumberOrdersClient) GetPhoneNumberOrder(ctx context.Context, in *GetPhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error) {
	out := new(PhoneNumberOrder)
	err := c.cc.Invoke(ctx, PhoneNumberOrders_GetPhoneNumberOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneNumberOrdersClient) ListPhoneNumberOrders(ctx context.Context, in *ListPhoneNumberOrdersRequest, opts ...grpc.CallOption) (*ListPhoneNumberOrdersResponse, error) {
	out := new(ListPhoneNumberOrdersResponse)
	err := c.cc.Invoke(ctx, PhoneNumberOrders_ListPhoneNumberOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneNumberOrdersClient) UpdatePhoneNumberOrder(ctx context.Context, in *UpdatePhoneNumberOrderRequest, opts ...grpc.CallOption) (*PhoneNumberOrder, error) {
	out := new(PhoneNumberOrder)
	err := c.cc.Invoke(ctx, PhoneNumberOrders_UpdatePhoneNumberOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneNumberOrdersClient) CancelPhoneNumberOrder(ctx context.Context, in *CancelPhoneNumberOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PhoneNumberOrders_CancelPhoneNumberOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneNumberOrdersServer is the server API for PhoneNumberOrders service.
// All implementations should embed UnimplementedPhoneNumberOrdersServer
// for forward compatibility
type PhoneNumberOrdersServer interface {
	// Creates an order to request phone numbers be added to a project.
	// The initial `LifecycleState` of a newly created order is
	// [PENDING][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.PENDING].
	CreatePhoneNumberOrder(context.Context, *CreatePhoneNumberOrderRequest) (*PhoneNumberOrder, error)
	// Returns a specific `PhoneNumberOrder`.
	GetPhoneNumberOrder(context.Context, *GetPhoneNumberOrderRequest) (*PhoneNumberOrder, error)
	// Lists of all `PhoneNumberOrder` resources in the specified project.
	ListPhoneNumberOrders(context.Context, *ListPhoneNumberOrdersRequest) (*ListPhoneNumberOrdersResponse, error)
	// Updates the specified `PhoneNumberOrder` resource.
	// Returns an error if the order is in state
	// [IN_PROGRESS][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.IN_PROGRESS]
	// or
	// [COMPLETED][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.COMPLETED].
	UpdatePhoneNumberOrder(context.Context, *UpdatePhoneNumberOrderRequest) (*PhoneNumberOrder, error)
	// Cancels an `PhoneNumberOrder`.
	// Returns an error if the order is in state
	// [IN_PROGRESS][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.IN_PROGRESS]
	// or
	// [COMPLETED][google.cloud.dialogflow.v2beta1.PhoneNumberOrder.LifecycleState.COMPLETED].
	CancelPhoneNumberOrder(context.Context, *CancelPhoneNumberOrderRequest) (*emptypb.Empty, error)
}

// UnimplementedPhoneNumberOrdersServer should be embedded to have forward compatible implementations.
type UnimplementedPhoneNumberOrdersServer struct {
}

func (UnimplementedPhoneNumberOrdersServer) CreatePhoneNumberOrder(context.Context, *CreatePhoneNumberOrderRequest) (*PhoneNumberOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePhoneNumberOrder not implemented")
}
func (UnimplementedPhoneNumberOrdersServer) GetPhoneNumberOrder(context.Context, *GetPhoneNumberOrderRequest) (*PhoneNumberOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhoneNumberOrder not implemented")
}
func (UnimplementedPhoneNumberOrdersServer) ListPhoneNumberOrders(context.Context, *ListPhoneNumberOrdersRequest) (*ListPhoneNumberOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPhoneNumberOrders not implemented")
}
func (UnimplementedPhoneNumberOrdersServer) UpdatePhoneNumberOrder(context.Context, *UpdatePhoneNumberOrderRequest) (*PhoneNumberOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhoneNumberOrder not implemented")
}
func (UnimplementedPhoneNumberOrdersServer) CancelPhoneNumberOrder(context.Context, *CancelPhoneNumberOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPhoneNumberOrder not implemented")
}

// UnsafePhoneNumberOrdersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneNumberOrdersServer will
// result in compilation errors.
type UnsafePhoneNumberOrdersServer interface {
	mustEmbedUnimplementedPhoneNumberOrdersServer()
}

func RegisterPhoneNumberOrdersServer(s grpc.ServiceRegistrar, srv PhoneNumberOrdersServer) {
	s.RegisterService(&PhoneNumberOrders_ServiceDesc, srv)
}

func _PhoneNumberOrders_CreatePhoneNumberOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhoneNumberOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneNumberOrdersServer).CreatePhoneNumberOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneNumberOrders_CreatePhoneNumberOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneNumberOrdersServer).CreatePhoneNumberOrder(ctx, req.(*CreatePhoneNumberOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneNumberOrders_GetPhoneNumberOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhoneNumberOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneNumberOrdersServer).GetPhoneNumberOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneNumberOrders_GetPhoneNumberOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneNumberOrdersServer).GetPhoneNumberOrder(ctx, req.(*GetPhoneNumberOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneNumberOrders_ListPhoneNumberOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhoneNumberOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneNumberOrdersServer).ListPhoneNumberOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneNumberOrders_ListPhoneNumberOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneNumberOrdersServer).ListPhoneNumberOrders(ctx, req.(*ListPhoneNumberOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneNumberOrders_UpdatePhoneNumberOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneNumberOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneNumberOrdersServer).UpdatePhoneNumberOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneNumberOrders_UpdatePhoneNumberOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneNumberOrdersServer).UpdatePhoneNumberOrder(ctx, req.(*UpdatePhoneNumberOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneNumberOrders_CancelPhoneNumberOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPhoneNumberOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneNumberOrdersServer).CancelPhoneNumberOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneNumberOrders_CancelPhoneNumberOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneNumberOrdersServer).CancelPhoneNumberOrder(ctx, req.(*CancelPhoneNumberOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhoneNumberOrders_ServiceDesc is the grpc.ServiceDesc for PhoneNumberOrders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhoneNumberOrders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.PhoneNumberOrders",
	HandlerType: (*PhoneNumberOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePhoneNumberOrder",
			Handler:    _PhoneNumberOrders_CreatePhoneNumberOrder_Handler,
		},
		{
			MethodName: "GetPhoneNumberOrder",
			Handler:    _PhoneNumberOrders_GetPhoneNumberOrder_Handler,
		},
		{
			MethodName: "ListPhoneNumberOrders",
			Handler:    _PhoneNumberOrders_ListPhoneNumberOrders_Handler,
		},
		{
			MethodName: "UpdatePhoneNumberOrder",
			Handler:    _PhoneNumberOrders_UpdatePhoneNumberOrder_Handler,
		},
		{
			MethodName: "CancelPhoneNumberOrder",
			Handler:    _PhoneNumberOrders_CancelPhoneNumberOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/dialogflow/v2beta1/phone_number_order.proto",
}
